Experiment 1
/work2/Sebas/conda_envs/PDPO/lib/python3.12/site-packages/torchdyn/numerics/odeint.py:83: UserWarning: Setting tolerances has no effect on fixed-step methods
  warn("Setting tolerances has no effect on fixed-step methods")
/work2/Sebas/Parametric_Density_Path_Opt/Parametric_pushforward/parametric_pushforward/visualization.py:416: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.07, 0.9, 0.95])
/work2/Sebas/conda_envs/PDPO/lib/python3.12/site-packages/torchdyn/numerics/odeint.py:83: UserWarning: Setting tolerances has no effect on fixed-step methods
  warn("Setting tolerances has no effect on fixed-step methods")
torch.Size([5000, 2]) torch.Size([5000, 10])
Traceback (most recent call last):
  File "/work2/Sebas/Parametric_Density_Path_Opt/Parametric_pushforward/density_path_optimization.py", line 368, in <module>
    run_experiments(str(dir_))
  File "/work2/Sebas/Parametric_Density_Path_Opt/Parametric_pushforward/density_path_optimization.py", line 284, in run_experiments
    bd0_distance.append(loss(samples_bd0,bd0_generated).detach().cpu().item())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work2/Sebas/conda_envs/PDPO/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work2/Sebas/conda_envs/PDPO/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work2/Sebas/conda_envs/PDPO/lib/python3.12/site-packages/geomloss/samples_loss.py", line 217, in forward
    B, N, M, D, l_x, α, l_y, β = self.check_shapes(l_x, α, x, l_y, β, y)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work2/Sebas/conda_envs/PDPO/lib/python3.12/site-packages/geomloss/samples_loss.py", line 347, in check_shapes
    raise ValueError(
ValueError: Input samples 'x' and 'y' should have the same last dimension.
